stages:
  - deploy

build_app_image:
  stage: deploy
  image: docker:1.11
  services:
    - docker:dind
  script:
    - docker version
    - docker build --file Dockerfile --tag cnc-app:latest .
    # push only for tags
    - "[[ -z $CI_COMMIT_TAG ]] && exit 0"
    - docker tag $CI_REGISTRY_IMAGE:latest cnc-app:$CI_BUILD_TAG
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker push cnc-app:$CI_BUILD_TAG

build_web_image:
  stage: deploy
  image: docker:1.11
  services:
    - docker:dind
  script:
    - docker version
    - docker build --file Dockerfile-nginx --tag cnc-web:latest .
    # push only for tags
    - "[[ -z $CI_COMMIT_TAG ]] && exit 0"
    - docker tag cnc-web:latest $CI_REGISTRY_IMAGE:$CI_BUILD_TAG
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker push cnc-web:$CI_BUILD_TAG
